name: Profile metrics

on:
  schedule:
    - cron: "0 3 * * *"   # her gün 06:00 (TR saati)
  workflow_dispatch:       # Actions sekmesinden elle çalıştırmak için

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 1) GitHub Stats kartı -> profile/stats.svg
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ygttncy
          filename: profile/stats.svg
          output_action: commit
          committer_message: "chore: update github stats"

          repositories_affiliations: owner, organization_member
          base: activity, repositories
          base_indepth: yes
          template: classic
          config_timezone: Europe/Istanbul

          extras_css: |
            svg { background: #111111; border: 1px solid #2A2A2A; border-radius: 10px; }
            body, .field, .language { color: #FAFAFA !important; }
            h2, h2 *, h3, h3 * { color: #FF6B1A !important; fill: #FF6B1A !important; }
            h2 { font-size: 18px !important; font-weight: 600 !important; }
            h2 svg, .field svg { fill: #FF6B1A !important; }
            .language small, small { color: #A3A3A3 !important; }

      # 2) Most Used Languages kartı -> profile/top-langs.svg
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ygttncy
          filename: profile/top-langs.svg
          output_action: commit
          committer_message: "chore: update top languages"

          repositories_affiliations: owner, organization_member
          repositories_forks: no
          base: ""
          template: classic
          plugin_languages: yes
          plugin_languages_ignored: java
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_languages_details: percentage

          extras_css: |
            svg { background: #111111; border: 1px solid #2A2A2A; border-radius: 10px; }
            body, .field, .language { color: #FAFAFA !important; }
            h2, h2 *, h3, h3 * { color: #FF6B1A !important; fill: #FF6B1A !important; }
            h2 { font-size: 18px !important; font-weight: 600 !important; }
            h2 svg, .field svg { fill: #FF6B1A !important; }
            .language small, small { color: #A3A3A3 !important; }
